services:
  telegram-queue-bot:
    image: ghcr.io/amir1330/queue-bot:latest
    container_name: telegram-queue-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - JITSI_DOMAIN=${JITSI_DOMAIN}
      - JITSI_JWT_SECRET=${JITSI_JWT_SECRET}
      - OWNER_ID=${OWNER_ID}
    volumes:
      - queue_bot_data:/app/data

volumes:
  queue_bot_data:
